services:
  - name: kafka-spring-mongo
    path: "/Users/Chandan/Documents/Personal Documents/Tech Practice/kafka-spring-mongo"
    type: maven

  - name: jenkins_gradle_project
    path: "/Users/Chandan/Documents/Personal Documents/Tech Practice/jenkins_gradle_project"
    type: gradle

  - name: spring-cucumber-gradle
    path: "/Users/Chandan/Documents/Personal Documents/Tech Practice/spring-cucumber-gradle"
    type: gradle

